language: python
dist: trusty
python: "3.6"
env:
  global:
    - BOTO_CONFIG=/dev/null
    - PIPENV_IGNORE_VIRTUALENVS=1
  matrix:
    - COMMAND="pipenv run pytest --cov-report term-missing --cov=pakkr"
branches:
  only: [master]
install:
  - pipenv sync --dev
script:
  - pipenv run $COMMAND
notifications:
webhooks:
